runtime: python39  # Указывает версию Python

instance_class: F2  # Класс инстанции, здесь F2 как пример

automatic_scaling:  # Параметры автоматического масштабирования
  target_cpu_utilization: 0.65  # Процент использования CPU, при достижении которого будет создан новый экземпляр
  min_instances: 1  # Минимальное количество экземпляров
  max_instances: 5  # Максимальное количество экземпляров
  min_idle_instances: automatic  # Минимальное количество экземпляров в режиме ожидания

entrypoint: python3 app.py  # Команда для запуска вашего приложения
